server {
    listen localhost:8080;
    server_name localhost;
    root ./www;
    index index.html;
    autoindex off;

    location /files {
        
        return 404 /errors/405.html;
    }
    location /secret {
        #return 501 ;
        return 598;
    }
}